spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.DerbyDialect
  datasource:
    url: jdbc:derby:memory:demo;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
